# K - Nearest Neighbors 

A program to use a K-nearest neighbor to predict class labels of test data. Euclidean distance is used as the distance metric. (K=5). The learned classifier is tested on test instances with unknown class labels, and the predicted class labels for the test instances is printed as output.

## Importing Libraries

In [0]:
#Importing required Libraries
import numpy as np
import copy
import pandas as pd

## Loading data

In [0]:
#Loading Data
f= open("data4.csv")
l= open("test4.csv")
fl=f.readlines()
ll=l.readlines()
#Formatting data
data3=np.array(fl)
test3=np.array(ll)
data = np.array([x.split(',') for x in data3], dtype=np.int)
test = np.array([x.split(',') for x in test3], dtype=np.int)

In [0]:
data

array([[1, 1, 1, 1, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0, 0, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 1],
       [1, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 0],
       [1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 1, 0, 0, 0, 1],
       [0, 1, 1, 1, 1, 1, 0, 1, 1],
       [0, 1, 1, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 0, 1, 0],
       [0, 1, 1, 1, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 1, 1, 1, 0, 1, 0],
       [1, 0, 0, 1, 0, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 0, 1, 1, 0, 1, 1]])

In [0]:
test

array([[0, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 0, 0, 0],
       [0, 1, 1, 1, 1, 0, 0, 0]])

### Data Summary

In [0]:
Number_Features=len(data[0])-1

Classes=list((np.unique(data[0:20,-1])))
    
Number_Classes=len(Classes)

print("Number of Training instances:",len(data))
print("Number of Test instances:",len(test))

print("Number of Features : ",Number_Features,"Number of Classes: ",Number_Classes)

print("Classes:",Classes)

Number of Training instances: 20
Number of Test instances: 4
Number of Features :  8 Number of Classes:  2
Classes: [0, 1]


## Data preperation

In [0]:
indices1=np.where((data[:,Number_Features]==0))
class1=(data[indices1])
indices2=np.where((data[:,Number_Features]==1))
class2=(data[indices2])
grouped_data=np.concatenate((class1,class2))

In [0]:
grouped_data

array([[1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 0, 1, 1, 1, 0, 1, 0],
       [1, 0, 1, 1, 1, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 1, 1, 1, 0, 1, 0],
       [1, 0, 0, 1, 0, 1, 1, 1, 0],
       [1, 0, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 1, 0, 0, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 1],
       [1, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 1, 0, 0, 0, 1],
       [0, 1, 1, 1, 1, 1, 0, 1, 1],
       [0, 1, 1, 1, 1, 1, 0, 0, 1],
       [0, 1, 1, 1, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 1, 0, 0, 0, 1],
       [0, 1, 1, 0, 1, 1, 0, 1, 1]])

In [0]:
Train_data_grouped=pd.DataFrame(grouped_data,index=None,columns=None,dtype=int)
Test_data=pd.DataFrame(test,index=None,columns=None,dtype=int)
Train_data_grouped

0  1  2  3  4  5  6  7  8
0   1  1  1  1  1  1  1  1  0
1   1  1  0  1  1  1  0  1  0
2   1  0  1  1  1  1  0  1  0
3   1  1  0  1  0  1  0  1  0
4   1  0  0  1  1  1  0  1  0
5   1  0  0  1  0  1  1  1  0
6   1  0  1  1  1  1  1  1  0
7   1  1  1  1  1  1  0  1  1
8   1  1  1  1  1  1  0  0  1
9   1  1  1  1  1  0  0  1  1
10  1  1  1  1  1  0  0  0  1
11  1  1  1  0  1  1  0  1  1
12  1  1  1  0  1  1  0  0  1
13  1  1  1  0  1  0  0  1  1
14  1  1  1  0  1  0  0  0  1
15  0  1  1  1  1  1  0  1  1
16  0  1  1  1  1  1  0  0  1
17  0  1  1  1  1  0  0  1  1
18  0  1  1  1  1  0  0  0  1
19  0  1  1  0  1  1  0  1  1

In [0]:
def split_features_classes(dataframe):
    features = dataframe.iloc[:, :-1]
    classes = dataframe.iloc[:, -1]
    return features, classes

In [0]:
train_features, train_classes = split_features_classes(Train_data_grouped)

## KNN algorithm

### Euclidean metric

In [0]:
import math

def euclidean_distance(first_object, second_object):
    distance = 0
    Number_Features = len(first_object)
    for f in range(Number_Features):
        distance += pow((first_object[f] - second_object[f]), 2)
    return math.sqrt(distance)

### Training and Testing

In [0]:
import numpy as np

def get_nearest_neighbours(train_features, focus_object, k):
    distances = []
    num_of_features = len(focus_object)
    for train_object in train_features.values:
        distance = euclidean_distance(train_object, focus_object)
        distances.append(distance)
    nearest=np.argsort(distances)
    return nearest[:k]

In [0]:
def get_majority_class(k_nearest_neighbours):
    votes_class_0=0
    votes_class_1=0
    for neighbour in k_nearest_neighbours:
        neighbour_class = train_classes.loc[neighbour]
        if neighbour_class == Classes[0]:
            votes_class_0 += 1
        elif neighbour_class == Classes[1]:
            votes_class_1 += 1
    if votes_class_0>votes_class_1:
        return 0
    else:
        return 1

In [0]:
num_test_samples = len(Test_data)
predicted_classes = []
for i in range(num_test_samples):
    test_object = Test_data.iloc[i]
    k_nearest_neighbours = get_nearest_neighbours(train_features, test_object, 5)
    predicted_class = get_majority_class(k_nearest_neighbours)
    print("Nearest 5 neighbors to Test Case",i,k_nearest_neighbours)
    print("Predicted Class:",predicted_class)
    predicted_classes.append(predicted_class)
print(predicted_classes)
  

Nearest 5 neighbors to Test Case 0 [ 0 15 17 16  7]
Predicted Class: 1
Nearest 5 neighbors to Test Case 1 [14  3  4  5 10]
Predicted Class: 0
Nearest 5 neighbors to Test Case 2 [14 18 19 17 16]
Predicted Class: 1
Nearest 5 neighbors to Test Case 3 [18 17 16 10  9]
Predicted Class: 1
[1, 0, 1, 1]
